-- https://supabase.com/docs/guides/local-development/cli-workflows?queryGroups=schema-approach&schema-approach=declarative#step-3-create-your-schema

CREATE TABLE public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    title TEXT NOT NULL,
    is_complete BOOLEAN DEFAULT false NOT NULL,
    is_public BOOLEAN DEFAULT false NOT NULL,
    user_id UUID REFERENCES auth.users (id) DEFAULT auth.uid() NOT NULL
);

ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

GRANT SELECT
    ON public.todos
    TO anon, authenticated;

GRANT SELECT, INSERT
    ON public.todos
    TO authenticated;

CREATE POLICY "Users can read their own todos"
    ON public.todos FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own todos"
    ON public.todos FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Anyone can read public todos"
    ON public.todos FOR SELECT
    TO anon, authenticated -- supabase roles
    USING (is_public = true);