-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.todos (
  id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  title       text                     NOT NULL,
  is_complete boolean                  DEFAULT false NOT NULL,
  is_public   boolean                  DEFAULT false NOT NULL,
  user_id     uuid                     DEFAULT auth.uid() NOT NULL
);

ALTER TABLE public.todos
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.todos
  ADD CONSTRAINT todos_pkey PRIMARY KEY (id);

ALTER TABLE public.todos
  ADD CONSTRAINT todos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.todos TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.todos TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.todos TO service_role;

CREATE POLICY "Anyone can read public todos" ON public.todos
  FOR SELECT
  TO anon, authenticated
  USING ((is_public = true));

CREATE POLICY "Users can create their own todos" ON public.todos
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can read their own todos" ON public.todos
  FOR SELECT
  USING ((auth.uid() = user_id));